# Generated by Django 3.2.6 on 2023-01-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('user_prof_type', models.CharField(max_length=255)),
                ('user_meeting_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_meeting', models.CharField(max_length=255)),
                ('scheduled_meeting_time', models.TimeField()),
                ('meeting_description', models.CharField(max_length=255)),
                ('meeting_location', models.CharField(max_length=255)),
                ('meeting_transcript', models.CharField(max_length=10000)),
                ('meeting_audio_file_link', models.CharField(max_length=255)),
                ('is_multilingual', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=255)),
                ('is_summarized', models.BooleanField(default=False)),
                ('meeting_summary', models.CharField(max_length=200)),
                ('summary_gen_date', models.DateField()),
                ('reading_time', models.CharField(max_length=30)),
                ('meeting_category_assgined', models.CharField(max_length=255)),
                ('model_used', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('top_keywords', models.CharField(max_length=255)),
                ('top_speaker', models.CharField(max_length=255)),
                ('roles_detected', models.CharField(max_length=255)),
                ('top_spent_time_person', models.CharField(max_length=255)),
                ('descions', models.CharField(max_length=1000)),
                ('highlights', models.CharField(max_length=1000)),
                ('is_good', models.BooleanField(default=False)),
                ('factual_consistency', models.CharField(max_length=255)),
                ('meeting_summary_old', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_info')),
            ],
        ),
    ]
