# Generated by Django 3.2.6 on 2023-01-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_meeting_category',
            field=models.CharField(default='tech', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_prof_type',
            field=models.CharField(default='SDE', max_length=255),
        ),
    ]
