# Generated by Django 3.2.6 on 2023-01-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230114_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='scheduled_meeting_time',
            field=models.TimeField(blank=True),
        ),
    ]
