# Generated by Django 3.2.6 on 2023-01-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_summary_scheduled_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='scheduled_meeting',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
