# Generated by Django 3.2.6 on 2023-01-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_summary_scheduled_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary_gen_date',
            field=models.DateField(null=True),
        ),
    ]
